name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: copia arquivos do repositorio
        uses: actions/checkout@v4

      - name: Instalar o python
        uses: actions/setuppython@v5
        with:
          python-version: '3.11'

