name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: copia arquivos do repositorio
        uses: actions/checkout@v4
      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar o poetry
        run: pip install poetry

      - name: Instalar dependencias do projeto
        run: poetry install --without doc
      
      - name: Rodar os testes
        run: poetry run task test

      - name: Subir cobertura para codecov
        uses:  codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}